# Generated by Django 5.1.4 on 2026-09-06 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('settlement', 'Quyết toán'), ('proposal', 'Đề xuất / Trình ký')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Danh mục')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Số tiền')),
                ('currency', models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD')], default='VND', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('paid', 'Đã chi')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
