# Generated by Django 5.1.4 on 2026-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='related_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Đường dẫn liên quan'),
        ),
    ]
