# Generated by Django 5.1.4 on 2026-09-10 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_add_related_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu duyệt', 'verbose_name_plural': 'Yêu cầu duyệt'},
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='currency',
            field=models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD')], default='VND', max_length=3, verbose_name='Đơn vị tiền tệ'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='request_type',
            field=models.CharField(choices=[('settlement', 'Quyết toán'), ('proposal', 'Đề xuất / Trình ký')], max_length=20, verbose_name='Loại yêu cầu'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('paid', 'Đã chi')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
