# Generated by Django 5.1.4 on 2026-09-12 03:02
# Chỉnh tay: thêm RunPython backfill CAVI cho dữ liệu cũ (toàn bộ dữ liệu hiện có đều là của CAVI —
# đã xác nhận đây là công ty duy nhất trước khi có LIVI/AVI).

import django.db.models.deletion
from django.db import migrations, models


def backfill_cavi(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    cavi = Company.objects.filter(code="CAVI").first()
    if not cavi:
        return
    ApprovalRequest = apps.get_model("approvals", "ApprovalRequest")
    ApprovalRequest.objects.filter(company__isnull=True).update(company=cavi)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalrequest_options_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.RunPython(backfill_cavi, noop_reverse),
    ]
