# Generated by Django 5.1.4 on 2026-09-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_approvalrequest_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='companies.company', verbose_name='Công ty'),
        ),
    ]
