# Generated by Django 5.1.4 on 2026-09-21 01:46

import companies.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_alter_approvalrequest_company'),
        ('companies', '0004_merge_cavi_avi_into_livi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='companies.company', verbose_name='Công ty'),
        ),
    ]
