# Generated by Django 5.1.4 on 2026-09-06 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(default='CAVI', max_length=50, verbose_name='Mã công ty')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('annual_current', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Phép năm nay')),
                ('annual_carried', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Phép năm cũ')),
                ('bonus_current', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Phép tăng thêm năm nay')),
                ('bonus_carried', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Phép tăng thêm năm cũ')),
                ('bonus_pending', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Phép tăng thêm chờ phân bổ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
