# Generated by Django 5.1.4 on 2026-09-10 12:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date'], 'verbose_name': 'Bản ghi chấm công', 'verbose_name_plural': 'Bản ghi chấm công'},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'verbose_name': 'Số ngày phép', 'verbose_name_plural': 'Số ngày phép'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ nhân viên', 'verbose_name_plural': 'Hồ sơ nhân viên'},
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='checked_in_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Giờ chấm công'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
