# Generated by Django 5.1.4 on 2026-09-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, choices=[('sales', 'Kinh doanh'), ('supply', 'Cung ứng'), ('operations', 'Vận hành'), ('accounting', 'Kế toán'), ('hr', 'Nhân sự'), ('management', 'Quản lý')], max_length=20, verbose_name='Phòng ban'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('probation', 'Đang thử việc'), ('active', 'Đang làm việc'), ('resigned', 'Đã nghỉ việc')], default='active', max_length=20, verbose_name='Trạng thái làm việc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hired_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày vào làm'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số CCCD/CMND'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Số điện thoại'),
        ),
    ]
