# Generated by Django 5.1.4 on 2026-09-10 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_employee_code(apps, schema_editor):
    # employee_code được thêm với giá trị rỗng cho các Profile đã có sẵn (AddField ghi thẳng qua SQL,
    # không chạy qua Profile.save() nên không tự sinh mã) — gán mã NV-00001 kiểu tăng dần theo id
    # cho những dòng còn trống, giữ đúng logic sinh mã ở Profile.save().
    Profile = apps.get_model("hr", "Profile")
    for profile in Profile.objects.filter(employee_code="").order_by("id"):
        code = f"NV-{profile.id:05d}"
        while Profile.objects.filter(employee_code=code).exclude(pk=profile.pk).exists():
            profile_id = int(code.split("-")[1]) + 1
            code = f"NV-{profile_id:05d}"
        profile.employee_code = code
        profile.save(update_fields=["employee_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_profile_address_profile_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='employment_status',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn hợp đồng'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu hợp đồng'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Loại hợp đồng'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Mã nhân viên'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(choices=[('official', 'Chính thức'), ('probation', 'Thử việc'), ('collaborator', 'Cộng tác viên')], default='official', max_length=20, verbose_name='Loại nhân sự'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='Mô tả công việc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cấp bậc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý trực tiếp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tên thường gọi'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resigned_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày nghỉ việc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa điểm làm việc'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_status',
            field=models.CharField(choices=[('active', 'Đang làm'), ('on_leave', 'Tạm nghỉ'), ('resigned', 'Đã nghỉ')], default='active', max_length=20, verbose_name='Tình trạng nhân sự'),
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('relationship', models.CharField(blank=True, max_length=100, verbose_name='Quan hệ')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='hr.profile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Người liên hệ khẩn cấp',
                'verbose_name_plural': 'Người liên hệ khẩn cấp',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_card', 'CCCD/CMND'), ('work_contract', 'Hợp đồng lao động'), ('contract_appendix', 'Phụ lục hợp đồng'), ('degree', 'Bằng cấp'), ('certificate', 'Chứng chỉ'), ('other', 'Khác')], max_length=20, verbose_name='Loại giấy tờ')),
                ('title', models.CharField(max_length=255, verbose_name='Tên giấy tờ')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Số giấy tờ')),
                ('issued_at', models.DateField(blank=True, null=True, verbose_name='Ngày cấp')),
                ('issued_place', models.CharField(blank=True, max_length=255, verbose_name='Nơi cấp')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn')),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_docs/%Y/%m/', verbose_name='File đính kèm')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr.profile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Giấy tờ nhân viên',
                'verbose_name_plural': 'Giấy tờ nhân viên',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(backfill_employee_code, migrations.RunPython.noop),
    ]
