# Generated by Django 5.1.4 on 2026-09-10 15:44

from django.conf import settings
from django.db import migrations


def backfill_missing_profiles(apps, schema_editor):
    # An toàn cho cả tài khoản tạo trước khi có signal tự tạo Hồ sơ (hr/signals.py). Model lịch sử
    # (apps.get_model) không có custom save() nên phải tự sinh employee_code ở đây, không gọi được
    # logic trong Profile.save() thật.
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("hr", "Profile")
    next_number = 1
    for user in User.objects.filter(profile__isnull=True).order_by("id"):
        while Profile.objects.filter(employee_code=f"NV-{next_number:05d}").exists():
            next_number += 1
        Profile.objects.create(user=user, employee_code=f"NV-{next_number:05d}")
        next_number += 1


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_profile_employment_status_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_missing_profiles, migrations.RunPython.noop),
    ]
