# Generated by Django 5.1.4 on 2026-09-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_backfill_missing_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['employee_code'], 'verbose_name': 'Hồ sơ nhân viên', 'verbose_name_plural': 'Hồ sơ nhân viên'},
        ),
    ]
