# Generated by Django 5.1.4 on 2026-09-10 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_profile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPenaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('bonus', 'Thưởng'), ('penalty', 'Phạt'), ('commission', 'Hoa hồng')], max_length=20, verbose_name='Loại')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số tiền')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Lý do')),
                ('effective_date', models.DateField(verbose_name='Ngày áp dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_penalty_records', to='hr.profile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Thưởng/phạt/hoa hồng',
                'verbose_name_plural': 'Thưởng/phạt/hoa hồng',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='CompensationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Ngày áp dụng')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Mức lương cơ bản')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Phụ cấp')),
                ('insurance_base', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Mức đóng bảo hiểm')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Ngân hàng')),
                ('bank_account', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản nhận lương')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản'), ('cash', 'Tiền mặt')], default='bank_transfer', max_length=20, verbose_name='Phương thức trả lương')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_records', to='hr.profile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Bản ghi lương',
                'verbose_name_plural': 'Lương',
                'ordering': ['-effective_date'],
            },
        ),
    ]
