# Generated by Django 5.1.4 on 2026-09-11 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_bonuspenaltyrecord_compensationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Trường thay đổi')),
                ('old_value', models.TextField(blank=True, verbose_name='Giá trị cũ')),
                ('new_value', models.TextField(blank=True, verbose_name='Giá trị mới')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm thay đổi')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='hr.profile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Nhật ký thay đổi hồ sơ',
                'verbose_name_plural': 'Nhật ký thay đổi hồ sơ',
                'ordering': ['-changed_at'],
            },
        ),
    ]
