# Generated by Django 5.1.4 on 2026-09-11 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_profilechangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('postgrad', 'Sau đại học'), ('university', 'Đại học'), ('college', 'Cao đẳng'), ('vocational', 'Trung cấp'), ('high_school', 'THPT'), ('other', 'Khác')], max_length=20, verbose_name='Trình độ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, max_length=255, verbose_name='Chuyên môn'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Kỹ năng'),
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Khoá đào tạo')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('trainer', models.CharField(blank=True, max_length=255, verbose_name='Người/đơn vị đào tạo')),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='Kết quả')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hr.profile', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Khoá đào tạo',
                'verbose_name_plural': 'Đào tạo & năng lực',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
    ]
