# Generated by Django 5.1.4 on 2026-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_profile_education_level_profile_major_profile_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('ceo', 'Tổng giám đốc'), ('director', 'Giám đốc'), ('head_of_dept', 'Trưởng phòng'), ('deputy_head', 'Phó phòng'), ('staff', 'Nhân viên'), ('intern', 'Thực tập sinh')], max_length=20, verbose_name='Cấp bậc'),
        ),
    ]
