# Generated by Django 5.1.4 on 2026-09-12 00:11
# Chỉnh tay: thêm companies TRƯỚC, backfill mọi Profile hiện có vào CAVI (company_code cũ luôn là
# "CAVI" — đã xác nhận trên cả local và production trước khi viết migration này), RỒI mới xoá
# company_code — đúng thứ tự để không mất thông tin, dù ở đây company_code chưa từng có giá trị
# nào khác "CAVI".

from django.db import migrations, models


def backfill_cavi_membership(apps, schema_editor):
    Profile = apps.get_model("hr", "Profile")
    Company = apps.get_model("companies", "Company")
    cavi = Company.objects.filter(code="CAVI").first()
    if not cavi:
        return
    for profile in Profile.objects.all():
        profile.companies.add(cavi)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('hr', '0011_alter_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='staff', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.RunPython(backfill_cavi_membership, noop_reverse),
        migrations.RemoveField(
            model_name='profile',
            name='company_code',
        ),
    ]
