# Generated by Django 5.1.4 on 2026-09-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_add_companies_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng')),
            ],
            options={
                'verbose_name': 'Phòng',
                'verbose_name_plural': 'Phòng',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['employee_code'], 'verbose_name': 'Hồ sơ nhân sự', 'verbose_name_plural': 'Hồ sơ nhân sự'},
        ),
        migrations.AddField(
            model_name='profile',
            name='personnel_document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giấy tờ nhân sự'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employee_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Id nhân sự'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(choices=[('official', 'Chính thức'), ('probation', 'Thử việc'), ('intern', 'Thực tập sinh'), ('collaborator', 'Cộng tác viên'), ('seasonal', 'Thời vụ'), ('other', 'Khác')], default='official', max_length=20, verbose_name='Loại nhân sự'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='staff', to='hr.room', verbose_name='Phòng'),
        ),
    ]
