# Generated by Django 5.1.4 on 2026-09-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_remove_job_title_and_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonuspenaltyrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bonuspenaltyrecord',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='compensationrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='compensationrecord',
            name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='BonusPenaltyRecord',
        ),
        migrations.DeleteModel(
            name='CompensationRecord',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
