# Generated by Django 5.1.4 on 2026-09-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_remove_compensation_bonus_leave_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Giấy tờ nhân sự', 'verbose_name_plural': 'Giấy tờ nhân sự'},
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='doc_type',
            field=models.CharField(choices=[('personal', 'Giấy tờ cá nhân'), ('contract', 'Hợp đồng'), ('decision', 'Quyết định'), ('degree_certificate', 'Bằng cấp & Chứng chỉ'), ('labor_residence', 'Lao động & Cư trú'), ('insurance', 'Bảo hiểm'), ('other', 'Khác')], max_length=20, verbose_name='Loại giấy tờ'),
        ),
    ]
