# Generated by Django 5.1.4 on 2026-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_convert_document_type_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'verbose_name': 'Liên hệ khẩn cấp', 'verbose_name_plural': 'Liên hệ khẩn cấp'},
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Id liên hệ khẩn cấp'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên liên hệ khẩn cấp'),
        ),
    ]
