# Generated by Django 5.1.4 on 2026-09-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_backfill_emergency_contact_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rooms',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
