# Generated by Django 5.1.4 on 2026-09-07 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên công việc')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Hạn hoàn thành')),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'Cần làm'), ('in_progress', 'Đang làm'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], default='todo', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tasks/%Y/%m/', verbose_name='File liên quan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người giao')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.partner', verbose_name='Khách hàng/đối tác liên quan')),
                ('related_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.activity', verbose_name='Hoạt động liên quan')),
            ],
            options={
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Chỉ tiêu doanh thu')),
                ('new_customer_target', models.IntegerField(default=0, verbose_name='Chỉ tiêu khách hàng mới')),
                ('quote_target', models.IntegerField(default=0, verbose_name='Chỉ tiêu báo giá')),
                ('order_target', models.IntegerField(default=0, verbose_name='Chỉ tiêu đơn hàng')),
                ('task_target', models.IntegerField(default=0, verbose_name='Chỉ tiêu công việc hoàn thành')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
