# Generated by Django 5.1.4 on 2026-09-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_task_kpitarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='follow_up_done',
            field=models.BooleanField(default=False, verbose_name='Đã nhắc follow-up'),
        ),
    ]
