# Generated by Django 5.1.4 on 2026-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_activity_follow_up_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ hẹn nhắc'),
        ),
    ]
