# Generated by Django 5.1.4 on 2026-09-07 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_activity_follow_up_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('status', models.CharField(choices=[('open', 'Đang hỏi giá'), ('quoted', 'Đã chốt giá'), ('cancelled', 'Huỷ')], default='open', max_length=20)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vốn')),
                ('floor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá sàn')),
                ('ceiling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá trần')),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_inquiries', to='crm.partner')),
                ('quoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người chốt giá')),
            ],
            options={
                'verbose_name_plural': 'Price inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceInquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_quote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.priceinquiry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
