# Generated by Django 5.1.4 on 2026-09-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_priceinquiry_priceinquirymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinquiry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='price_inquiries/%Y/%m/', verbose_name='Hình ảnh'),
        ),
    ]
