# Generated by Django 5.1.4 on 2026-09-07 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_priceinquiry_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('I', 'Loại I'), ('II', 'Loại II'), ('III', 'Loại III')], max_length=5, verbose_name='Phân loại')),
                ('group_name', models.CharField(max_length=255, verbose_name='Nhóm mặt hàng')),
                ('group_code', models.CharField(max_length=10, verbose_name='Mã nhóm')),
                ('item_code', models.CharField(max_length=20, unique=True, verbose_name='Mã mặt hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên mặt hàng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='ĐVT')),
                ('floor_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Giá sàn (%)')),
                ('ceiling_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Giá trần (%)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group_code', 'item_code'],
            },
        ),
        migrations.CreateModel(
            name='PriceInquiryQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Tên mặt hàng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='ĐVT')),
                ('floor_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Giá sàn (%)')),
                ('ceiling_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Giá trần (%)')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Đơn giá vốn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='crm.priceinquiry')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pricelistitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
