# Generated by Django 5.1.4 on 2026-09-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_seed_price_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceinquiryquoteline',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='group_name',
            field=models.CharField(max_length=255, verbose_name='Nhóm dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='item_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên dịch vụ'),
        ),
    ]
