# Generated by Django 5.1.4 on 2026-09-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_reseed_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinquiryquoteline',
            name='note',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
    ]
