# Generated by Django 5.1.4 on 2026-09-08 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_add_quoteline_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='crm.priceinquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Tên dịch vụ')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='ĐVT')),
                ('floor_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Giá sàn (%)')),
                ('ceiling_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Giá trần (%)')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Đơn giá vốn')),
                ('note', models.TextField(blank=True, verbose_name='Mô tả')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
