# Generated by Django 5.1.4 on 2026-09-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_add_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationline',
            name='ceiling_pct',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='floor_pct',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='note',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='quotationline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='item_name',
            field=models.CharField(max_length=255, verbose_name='Mô tả'),
        ),
    ]
