# Generated by Django 5.1.4 on 2026-09-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('crm', '0017_simplify_quotation_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pending_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalrequest'),
        ),
    ]
