# Generated by Django 5.1.4 on 2026-09-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_quotation_pending_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationline',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mô tả'),
        ),
    ]
