# Generated by Django 5.1.4 on 2026-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_quotationline_item_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pending_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
