# Generated by Django 5.1.4 on 2026-09-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_quotation_pending_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to='crm.quotation'),
        ),
    ]
