# Generated by Django 5.1.4 on 2026-09-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_order_source_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Thu hộ (COD)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=255, verbose_name='Điểm giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, verbose_name='Điểm lấy hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Khối lượng (kg)'),
        ),
    ]
