# Generated by Django 5.1.4 on 2026-09-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_order_shipping_label_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ceiling_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tỷ lệ giá trần (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='ceiling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá trần'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tỷ lệ giá sàn (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá sàn'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='ceiling_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tỷ lệ giá trần (%)'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='floor_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tỷ lệ giá sàn (%)'),
        ),
    ]
