# Generated by Django 5.1.4 on 2026-09-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_floor_ceiling_pct_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
