# Generated by Django 5.1.4 on 2026-09-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_quotation_saved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='crm.priceinquiry'),
        ),
    ]
