# Generated by Django 5.1.4 on 2026-09-10 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_quotation_allow_multiple_per_inquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Kinh doanh xác nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm ghi nhận'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vận hành ghi nhận'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Số lượng thực nhận'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_receipt', 'Chờ vận hành nhận hàng'), ('pending_confirmation', 'Chờ Kinh doanh xác nhận'), ('new', 'Mới'), ('processing', 'Đang xử lý'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], default='pending_receipt', max_length=20),
        ),
    ]
