# Generated by Django 5.1.4 on 2026-09-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_order_receiving_confirmation_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả lô hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='orders/%Y/%m/', verbose_name='Hình ảnh'),
        ),
    ]
