# Generated by Django 5.1.4 on 2026-09-10 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_alter_approvalrequest_options_and_more'),
        ('crm', '0027_order_description_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_at'], 'verbose_name': 'Hoạt động khách hàng', 'verbose_name_plural': 'Hoạt động khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='kpitarget',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Chỉ tiêu KPI', 'verbose_name_plural': 'Chỉ tiêu KPI'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông báo nội bộ', 'verbose_name_plural': 'Thông báo nội bộ'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Phiếu nhận hàng / Đơn hàng', 'verbose_name_plural': 'Phiếu nhận hàng / Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Dòng hàng', 'verbose_name_plural': 'Dòng hàng'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.AlterModelOptions(
            name='priceinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hỏi giá', 'verbose_name_plural': 'Hỏi giá'},
        ),
        migrations.AlterModelOptions(
            name='priceinquirymessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Tin nhắn hỏi giá', 'verbose_name_plural': 'Tin nhắn hỏi giá'},
        ),
        migrations.AlterModelOptions(
            name='priceinquiryquoteline',
            options={'ordering': ['id'], 'verbose_name': 'Dòng dịch vụ cấu thành', 'verbose_name_plural': 'Dòng dịch vụ cấu thành'},
        ),
        migrations.AlterModelOptions(
            name='pricelistitem',
            options={'ordering': ['group_code', 'item_code'], 'verbose_name': 'Bảng giá dịch vụ', 'verbose_name_plural': 'Bảng giá dịch vụ'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Báo giá', 'verbose_name_plural': 'Báo giá'},
        ),
        migrations.AlterModelOptions(
            name='quotationline',
            options={'ordering': ['id'], 'verbose_name': 'Dòng báo giá', 'verbose_name_plural': 'Dòng báo giá'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_at', '-created_at'], 'verbose_name': 'Công việc', 'verbose_name_plural': 'Công việc'},
        ),
        migrations.AlterModelOptions(
            name='tierupgraderequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu nâng hạng', 'verbose_name_plural': 'Yêu cầu nâng hạng'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Cuộc gọi'), ('email', 'Email'), ('message', 'Tin nhắn'), ('meeting', 'Gặp mặt'), ('note', 'Ghi chú'), ('task', 'Công việc cần làm'), ('follow_up', 'Việc cần theo dõi lại'), ('appointment', 'Lịch hẹn / cuộc họp'), ('opportunity', 'Cơ hội kinh doanh'), ('quote', 'Báo giá'), ('order', 'Đơn hàng'), ('contract', 'Hợp đồng'), ('payment', 'Thanh toán'), ('support_request', 'Yêu cầu hỗ trợ'), ('complaint', 'Khiếu nại'), ('issue_handling', 'Xử lý sự cố'), ('post_sale_care', 'Chăm sóc sau bán hàng')], max_length=20, verbose_name='Loại hoạt động'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.partner', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cần theo dõi lại'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='follow_up_done',
            field=models.BooleanField(default=False, verbose_name='Đã nhắc việc cần theo dõi lại'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('not_processed', 'Chưa xử lý'), ('in_progress', 'Đang xử lý'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], default='not_processed', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='month',
            field=models.IntegerField(verbose_name='Tháng'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='year',
            field=models.IntegerField(verbose_name='Năm'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.partner', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to='crm.quotation', verbose_name='Báo giá gốc'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_receipt', 'Chờ vận hành nhận hàng'), ('pending_confirmation', 'Chờ Kinh doanh xác nhận'), ('new', 'Mới'), ('processing', 'Đang xử lý'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], default='pending_receipt', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order', verbose_name='Phiếu nhận hàng'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_inquiries', to='crm.partner', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm chốt giá'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='status',
            field=models.CharField(choices=[('open', 'Đang hỏi giá'), ('quoted', 'Đã chốt giá'), ('cancelled', 'Huỷ')], default='open', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='priceinquirymessage',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi'),
        ),
        migrations.AlterField(
            model_name='priceinquirymessage',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='priceinquirymessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='priceinquirymessage',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.priceinquiry', verbose_name='Hỏi giá'),
        ),
        migrations.AlterField(
            model_name='priceinquirymessage',
            name='is_quote',
            field=models.BooleanField(default=False, verbose_name='Là tin chốt giá'),
        ),
        migrations.AlterField(
            model_name='priceinquiryquoteline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='priceinquiryquoteline',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='priceinquiryquoteline',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='crm.priceinquiry', verbose_name='Hỏi giá'),
        ),
        migrations.AlterField(
            model_name='priceinquiryquoteline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.pricelistitem', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang sử dụng'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='crm.priceinquiry', verbose_name='Hỏi giá'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pending_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='approvals.approvalrequest', verbose_name='Đề xuất đang chờ duyệt'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pending_snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Nội dung đề xuất đang chờ'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm lưu gần nhất'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='crm.quotation', verbose_name='Báo giá'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=10, verbose_name='Độ ưu tiên'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Cần làm'), ('in_progress', 'Đang làm'), ('done', 'Hoàn thành'), ('cancelled', 'Huỷ')], default='todo', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='tierupgraderequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='tierupgraderequest',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_requests', to='crm.partner', verbose_name='Đối tác'),
        ),
        migrations.AlterField(
            model_name='tierupgraderequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='tierupgraderequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt'),
        ),
        migrations.AlterField(
            model_name='tierupgraderequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AlterField(
            model_name='tierupgraderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
