# Generated by Django 5.1.4 on 2026-09-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_activity_options_alter_kpitarget_options_and_more'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.ward', verbose_name='Phường/Xã giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.ward', verbose_name='Phường/Xã lấy hàng'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.country', verbose_name='Quốc gia'),
        ),
        migrations.AddField(
            model_name='partner',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.district', verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='partner',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.province', verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='partner',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Số nhà, đường'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.ward', verbose_name='Phường/Xã'),
        ),
    ]
