# Generated by Django 5.1.4 on 2026-09-11 14:25
# Chỉnh tay: thêm bước RunPython để chuyển dữ liệu partner_type ("customer"/"supplier"/"both")
# cũ sang is_customer/is_supplier mới TRƯỚC khi xoá field cũ — nếu không, dữ liệu thật trên
# production (đã có Đối tác) sẽ mất sạch giá trị phân loại.

from django.db import migrations, models


def backfill_customer_supplier_flags(apps, schema_editor):
    Partner = apps.get_model("crm", "Partner")
    Partner.objects.filter(partner_type="customer").update(is_customer=True, is_supplier=False)
    Partner.objects.filter(partner_type="supplier").update(is_customer=False, is_supplier=True)
    Partner.objects.filter(partner_type="both").update(is_customer=True, is_supplier=True)


def reverse_backfill(apps, schema_editor):
    Partner = apps.get_model("crm", "Partner")
    Partner.objects.filter(is_customer=True, is_supplier=True).update(partner_type="both")
    Partner.objects.filter(is_customer=True, is_supplier=False).update(partner_type="customer")
    Partner.objects.filter(is_customer=False, is_supplier=True).update(partner_type="supplier")


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_order_delivery_ward_order_pickup_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Là khách hàng'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='Là nhà cung cấp'),
        ),
        migrations.RunPython(backfill_customer_supplier_flags, reverse_backfill),
        migrations.RemoveField(
            model_name='partner',
            name='partner_type',
        ),
    ]
