# Generated by Django 5.1.4 on 2026-09-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_remove_partner_partner_type_partner_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='district',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='province',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='street_address',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='ward',
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ'),
        ),
    ]
