# Generated by Django 5.1.4 on 2026-09-11 16:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_remove_partner_country_remove_partner_district_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInquiryQuoteLineBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Đơn giá vốn chào')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người chào giá')),
                ('quote_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='crm.priceinquiryquoteline', verbose_name='Dòng dịch vụ cấu thành')),
            ],
            options={
                'verbose_name': 'Báo giá cạnh tranh',
                'verbose_name_plural': 'Báo giá cạnh tranh',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='priceinquiryquoteline',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.priceinquiryquotelinebid', verbose_name='Báo giá thắng'),
        ),
    ]
