# Generated by Django 5.1.4 on 2026-09-12 03:02
# Chỉnh tay: thêm RunPython backfill CAVI cho dữ liệu cũ (toàn bộ dữ liệu hiện có đều là của CAVI —
# đã xác nhận đây là công ty duy nhất trước khi có LIVI/AVI).

import django.db.models.deletion
from django.db import migrations, models


def backfill_cavi(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    cavi = Company.objects.filter(code="CAVI").first()
    if not cavi:
        return
    Activity = apps.get_model("crm", "Activity")
    KPITarget = apps.get_model("crm", "KPITarget")
    Notice = apps.get_model("crm", "Notice")
    Order = apps.get_model("crm", "Order")
    Activity.objects.filter(company__isnull=True).update(company=cavi)
    KPITarget.objects.filter(company__isnull=True).update(company=cavi)
    Notice.objects.filter(company__isnull=True).update(company=cavi)
    Order.objects.filter(company__isnull=True).update(company=cavi)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('crm', '0032_priceinquiryquotelinebid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='notice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.RunPython(backfill_cavi, noop_reverse),
    ]
