# Generated by Django 5.1.4 on 2026-09-12 03:02
# Chỉnh tay: thêm RunPython backfill CAVI cho PriceInquiry/PriceListItem/Task/TierUpgradeRequest.

import django.db.models.deletion
from django.db import migrations, models


def backfill_cavi(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    cavi = Company.objects.filter(code="CAVI").first()
    if not cavi:
        return
    PriceInquiry = apps.get_model("crm", "PriceInquiry")
    PriceListItem = apps.get_model("crm", "PriceListItem")
    Task = apps.get_model("crm", "Task")
    TierUpgradeRequest = apps.get_model("crm", "TierUpgradeRequest")
    PriceInquiry.objects.filter(company__isnull=True).update(company=cavi)
    PriceListItem.objects.filter(company__isnull=True).update(company=cavi)
    Task.objects.filter(company__isnull=True).update(company=cavi)
    TierUpgradeRequest.objects.filter(company__isnull=True).update(company=cavi)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('crm', '0033_activity_company_kpitarget_company_notice_company_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Hàng hoá'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_inquiries', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='priceinquiryquoteline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Hàng hoá'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='quotationline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Hàng hoá'),
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AddField(
            model_name='tierupgraderequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tier_requests', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.RunPython(backfill_cavi, noop_reverse),
    ]
