# Generated by Django 5.1.4 on 2026-09-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('crm', '0034_orderitem_product_priceinquiry_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='priceinquiry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_inquiries', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='companies.company', verbose_name='Công ty'),
        ),
    ]
