# Generated by Django 5.1.4 on 2026-09-12 04:09
# Chỉnh tay: thêm RunPython backfill CAVI cho Đối tác cũ (toàn bộ đối tác hiện có đều phát sinh từ
# giao dịch với CAVI — công ty duy nhất tồn tại trước khi có LIVI/AVI).

from django.db import migrations, models


def backfill_cavi(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    cavi = Company.objects.filter(code="CAVI").first()
    if not cavi:
        return
    Partner = apps.get_model("crm", "Partner")
    for partner in Partner.objects.all():
        partner.companies.add(cavi)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('crm', '0035_alter_activity_company_alter_order_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='partners', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.RunPython(backfill_cavi, noop_reverse),
    ]
