# Generated by Django 5.1.4 on 2026-09-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_partner_assigned_to_profile_step3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TierUpgradeRequest',
        ),
    ]
