# Generated by Django 5.1.4 on 2026-09-20 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_remove_tier_auto_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_at'], 'verbose_name': 'Hoạt động đối tác', 'verbose_name_plural': 'Hoạt động đối tác'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.partner', verbose_name='Đối tác'),
        ),
    ]
