# Generated by Django 5.1.4 on 2026-09-20 14:56
#
# Chỉnh tay: bỏ unique=True ra khỏi field "code" ở bước này — bảng đã có sẵn dữ liệu, thêm field
# unique với default rỗng cho MỌI dòng cùng lúc thì các dòng cùng "" đụng UNIQUE constraint ngay lập
# tức (xem 0038_backfill_partner_codes.py/0039_partner_code_unique.py cho đúng mẫu 3 bước này).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_rename_activity_to_partner_activity'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinquiry',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Id hỏi giá'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.country', verbose_name='Quốc gia'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.district', verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên hàng'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.province', verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Số lượng'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Số nhà, đường'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Đơn vị'),
        ),
        migrations.AddField(
            model_name='priceinquiry',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.ward', verbose_name='Phường/Xã'),
        ),
    ]
