# Generated by Django 5.1.4 on 2026-09-20 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_cavi_avi_into_livi'),
        ('crm', '0047_price_inquiry_code_unique'),
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceInquiry',
            new_name='PriceRequest',
        ),
    ]
