# Generated by Django 5.1.4 on 2026-09-21 01:04
#
# Chỉnh tay: tách 3 bước an toàn — migration này CHỈ thêm field/model mới (không mất dữ liệu). Việc
# xoá field cũ trên PriceRequest (item_name/quantity/unit/image/cost_price/.../quoted_at) chuyển
# sang 0051, SAU KHI 0050 đã copy dữ liệu cũ sang PriceRequestItem + remap status — đúng mẫu 3 bước
# đã dùng nhiều lần trong dự án khi đổi cấu trúc field có dữ liệu sẵn.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_cavi_avi_into_livi'),
        ('crm', '0048_rename_priceinquiry_to_pricerequest'),
        ('hr', '0027_remove_profile_rooms_delete_room'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu giá', 'verbose_name_plural': 'Yêu cầu giá'},
        ),
        migrations.AddField(
            model_name='order',
            name='source_price_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to='crm.pricerequest', verbose_name='Yêu cầu giá gốc'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse', verbose_name='Kho xuất'),
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_requests', to='hr.profile', verbose_name='Nhân sự phụ trách'),
        ),
        migrations.AddField(
            model_name='pricerequest',
            name='direction',
            field=models.CharField(blank=True, choices=[('vn_to_kh', 'Việt Nam → Campuchia'), ('kh_to_vn', 'Campuchia → Việt Nam')], max_length=20, verbose_name='Chiều mua bán'),
        ),
        migrations.AlterField(
            model_name='pricerequest',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Id yêu cầu giá'),
        ),
        migrations.AlterField(
            model_name='pricerequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_requests', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='pricerequest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='crm.partner', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='pricerequest',
            name='status',
            field=models.CharField(choices=[('cho_cung_ung', 'Chờ Cung ứng'), ('da_kiem_tra_nguon_hang', 'Đã kiểm tra nguồn hàng'), ('cho_tinh_gia', 'Chờ tính giá'), ('cho_duyet', 'Chờ duyệt giá'), ('da_duyet', 'Đã duyệt giá'), ('da_gui_khach', 'Đã gửi khách'), ('khach_dong_y', 'Khách đồng ý'), ('khach_tu_choi', 'Khách từ chối'), ('dang_thuong_luong', 'Đang thương lượng'), ('huy', 'Huỷ')], default='cho_cung_ung', max_length=30, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='PriceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(editable=False, verbose_name='Phiên bản')),
                ('profit_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Tỷ lệ lợi nhuận (%)')),
                ('approval_status', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối'), ('yeu_cau_sua', 'Yêu cầu sửa')], default='cho_duyet', max_length=20, verbose_name='Trạng thái duyệt')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('price_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='crm.pricerequest', verbose_name='Yêu cầu giá')),
            ],
            options={
                'verbose_name': 'Tính giá',
                'verbose_name_plural': 'Tính giá',
                'ordering': ['price_request_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='source_price_calculation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to='crm.pricecalculation', verbose_name='Phiên bản tính giá gốc'),
        ),
        migrations.CreateModel(
            name='PriceRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='Tên hàng')),
                ('image', models.FileField(blank=True, null=True, upload_to='price_requests/%Y/%m/', verbose_name='Hình ảnh sản phẩm')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Số lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('source_status', models.CharField(choices=[('chua_xac_dinh', 'Chưa xác định'), ('ton_kho', 'Tồn kho'), ('mua_moi', 'Mua mới'), ('ton_kho_va_mua_bo_sung', 'Tồn kho + mua bổ sung')], default='chua_xac_dinh', editable=False, max_length=30, verbose_name='Nguồn hàng')),
                ('price_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.pricerequest', verbose_name='Yêu cầu giá')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Hàng hoá')),
            ],
            options={
                'verbose_name': 'Dòng sản phẩm yêu cầu giá',
                'verbose_name_plural': 'Dòng sản phẩm yêu cầu giá',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Giá mua')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Vận chuyển')),
                ('customs_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Hải quan')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Chi phí khác')),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Giá đề xuất')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Giá chốt')),
                ('price_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.pricecalculation', verbose_name='Tính giá')),
                ('price_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_items', to='crm.pricerequestitem', verbose_name='Dòng yêu cầu giá')),
            ],
            options={
                'verbose_name': 'Dòng tính giá',
                'verbose_name_plural': 'Dòng tính giá',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Id đề nghị mua')),
                ('purchase_type', models.CharField(choices=[('theo_don_khach', 'Mua theo nhu cầu khách'), ('nhap_kho', 'Mua nhập kho')], max_length=20, verbose_name='Loại mua')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='inventory.warehouse', verbose_name='Kho nhận')),
            ],
            options={
                'verbose_name': 'Đề nghị mua hàng',
                'verbose_name_plural': 'Đề nghị mua hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='Tên hàng')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.product', verbose_name='Hàng hoá')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.purchaserequest', verbose_name='Đề nghị mua hàng')),
            ],
            options={
                'verbose_name': 'Dòng đề nghị mua hàng',
                'verbose_name_plural': 'Dòng đề nghị mua hàng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng phân bổ')),
                ('price_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_allocations', to='crm.pricerequestitem', verbose_name='Dòng yêu cầu giá')),
                ('purchase_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='crm.purchaserequestitem', verbose_name='Dòng đề nghị mua')),
            ],
            options={
                'verbose_name': 'Phân bổ đề nghị mua',
                'verbose_name_plural': 'Phân bổ đề nghị mua',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Giá mua')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị')),
                ('pickup_point', models.CharField(blank=True, max_length=255, verbose_name='Điểm lấy hàng')),
                ('total_packages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng số kiện')),
                ('package_dimensions', models.CharField(blank=True, max_length=255, verbose_name='Kích thước kiện')),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng CBM')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng trọng lượng (kg)')),
                ('available_at', models.DateField(blank=True, null=True, verbose_name='Thời gian có hàng')),
                ('payment_terms', models.CharField(blank=True, max_length=255, verbose_name='Điều kiện thanh toán')),
                ('delivery_terms', models.CharField(blank=True, max_length=255, verbose_name='Điều kiện giao nhận')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_selected', models.BooleanField(default=False, verbose_name='Là nguồn mua chính')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('purchase_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='crm.purchaserequestitem', verbose_name='Dòng đề nghị mua')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='crm.partner', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Báo giá nhà cung cấp',
                'verbose_name_plural': 'Báo giá nhà cung cấp',
                'ordering': ['created_at'],
            },
        ),
    ]
