# Generated by Django 5.1.4 on 2026-09-21 01:46

import companies.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_cavi_avi_into_livi'),
        ('crm', '0051_remove_pricerequest_old_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='kpitarget',
            name='company',
            field=models.ForeignKey(blank=True, default=companies.utils.get_default_company_id, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='company',
            field=models.ForeignKey(blank=True, default=companies.utils.get_default_company_id, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='price_list_items', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='pricerequest',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='price_requests', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, default=companies.utils.get_default_company_id, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='companies.company', verbose_name='Công ty'),
        ),
    ]
