# Generated by Django 5.1.4 on 2026-09-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_alter_activity_company_alter_kpitarget_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerequest',
            name='direction',
        ),
    ]
