# Generated by Django 5.1.4 on 2026-09-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_remove_pricerequest_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierquote',
            name='selection_note',
            field=models.TextField(blank=True, verbose_name='Lý do chọn'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vận chuyển'),
        ),
    ]
