# Generated by Django 5.1.4 on 2026-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_add_supplier_quote_shipping_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerequestitem',
            name='estimated_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vốn tạm tính'),
        ),
    ]
