# Generated by Django 5.1.4 on 2026-09-21 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_add_price_request_item_estimated_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('price_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_quotes', to='crm.pricerequestitem', verbose_name='Dòng yêu cầu giá')),
            ],
            options={
                'verbose_name': 'Báo giá vốn',
                'verbose_name_plural': 'Báo giá vốn',
                'ordering': ['-created_at'],
            },
        ),
    ]
