# Generated by Django 5.1.4 on 2026-09-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_add_cost_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id yêu cầu giá'),
        ),
    ]
