# Generated by Django 5.1.4 on 2026-09-22 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_alter_pricerequest_id'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costquote',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.country', verbose_name='Quốc gia'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.district', verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mặt hàng'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.province', verbose_name='Tỉnh/Thành phố'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Số lượng'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vốn vận chuyển'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Số nhà, đường'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tổng giá vốn'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='total_dimensions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tổng kích thước'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng trọng lượng'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='ĐVT'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vốn đơn vị'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='unit_dimensions',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kích thước đơn vị'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trọng lượng đơn vị'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geo.ward', verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='costquote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id trả lời yêu cầu giá'),
        ),
        migrations.AlterField(
            model_name='costquote',
            name='note',
            field=models.TextField(blank=True, verbose_name='Mô tả thêm'),
        ),
    ]
