# Generated by Django 5.1.4 on 2026-09-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_costquote_country_costquote_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costquote',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='total_dimensions',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='total_weight_kg',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='unit_dimensions',
        ),
        migrations.RemoveField(
            model_name='costquote',
            name='unit_weight_kg',
        ),
        migrations.CreateModel(
            name='CostQuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, verbose_name='Mặt hàng')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Số lượng')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='ĐVT')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vốn đơn vị')),
                ('unit_dimensions', models.CharField(blank=True, max_length=255, verbose_name='Kích thước đơn vị')),
                ('unit_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trọng lượng đơn vị')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Tổng giá vốn')),
                ('total_dimensions', models.CharField(blank=True, max_length=255, verbose_name='Tổng kích thước')),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tổng trọng lượng')),
                ('cost_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.costquote', verbose_name='Câu trả lời')),
            ],
            options={
                'verbose_name': 'Dòng mặt hàng trả lời yêu cầu giá',
                'verbose_name_plural': 'Dòng mặt hàng trả lời yêu cầu giá',
                'ordering': ['id'],
            },
        ),
    ]
