# Generated by Django 5.1.4 on 2026-09-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_remove_costquote_item_name_remove_costquote_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costquoteitem',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='costquoteitem',
            name='total_dimensions',
        ),
        migrations.RemoveField(
            model_name='costquoteitem',
            name='total_weight_kg',
        ),
        migrations.RemoveField(
            model_name='costquoteitem',
            name='unit_dimensions',
        ),
        migrations.AddField(
            model_name='costquoteitem',
            name='unit_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cao (cm)'),
        ),
        migrations.AddField(
            model_name='costquoteitem',
            name='unit_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dài (cm)'),
        ),
        migrations.AddField(
            model_name='costquoteitem',
            name='unit_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rộng (cm)'),
        ),
        migrations.AlterField(
            model_name='costquoteitem',
            name='unit_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Trọng lượng đơn vị (kg)'),
        ),
    ]
