# Generated by Django 5.1.4 on 2026-09-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_remove_costquoteitem_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costquote',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='costquote',
            name='shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá cước vận chuyển'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='shipping_rate_basis',
            field=models.CharField(choices=[('kg', 'kg'), ('m3', 'm3')], default='kg', max_length=10, verbose_name='Tính cước theo'),
        ),
    ]
