# Generated by Django 5.1.4 on 2026-09-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_remove_costquote_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costquote',
            name='shipping_rate_basis',
            field=models.CharField(choices=[('kg', 'kg'), ('m3', 'm3'), ('total', 'Tổng cố định')], default='kg', max_length=10, verbose_name='Tính cước theo'),
        ),
    ]
