# Generated by Django 5.1.4 on 2026-09-22 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_alter_costquote_shipping_rate_basis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costquote',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='costquote',
            name='available_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày có hàng'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='carrier_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Đơn vị vận chuyển'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='NCC đã xác nhận'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='delivery_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costquote',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='costquote',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='costquote',
            name='supersedes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='crm.costquote'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='costquote',
            name='tax_basis',
            field=models.CharField(choices=[('unknown', 'Chưa rõ thuế'), ('included', 'Đã gồm thuế'), ('excluded', 'Chưa gồm thuế')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='costquote',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Hiệu lực đến'),
        ),
        migrations.CreateModel(
            name='FreightOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('basis', models.CharField(choices=[('kg', 'kg'), ('m3', 'm3'), ('total', 'Tổng cố định')], default='total', max_length=10)),
                ('confirmed', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('tax_basis', models.CharField(choices=[('unknown', 'Chưa rõ thuế'), ('included', 'Đã gồm thuế'), ('excluded', 'Chưa gồm thuế')], default='unknown', max_length=20)),
                ('terms', models.CharField(blank=True, max_length=500)),
                ('delivery_snapshot', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('goods_quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_offers', to='crm.costquote')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='crm.freightoffer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SourcingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Chờ duyệt'), ('approved', 'Đã chốt'), ('rejected', 'Không chọn')], default='proposed', max_length=20)),
                ('reason', models.TextField()),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_proposals', to=settings.AUTH_USER_MODEL)),
                ('freight_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sourcing_plans', to='crm.freightoffer')),
                ('goods_quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sourcing_plans', to='crm.costquote')),
                ('price_request_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sourcing_plans', to='crm.pricerequestitem')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('price_request_item',), name='one_approved_sourcing_plan')],
            },
        ),
    ]
