# Generated by Django 5.1.4 on 2026-09-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_sourcing_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='costquote',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competing_quotes', to='crm.costquote'),
        ),
    ]
