# Generated by Django 5.1.4 on 2026-09-13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def create_finance_records(apps, schema_editor):
    Order = apps.get_model("crm", "Order")
    OrderFinance = apps.get_model("finance", "OrderFinance")
    existing = set(OrderFinance.objects.values_list("order_id", flat=True))
    OrderFinance.objects.bulk_create(
        OrderFinance(order_id=order_id)
        for order_id in Order.objects.values_list("id", flat=True)
        if order_id not in existing
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0036_partner_companies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderFinance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency", models.CharField(choices=[("VND", "VNĐ"), ("USD", "USD"), ("LAK", "Kíp Lào"), ("KHR", "Riel Campuchia")], default="VND", max_length=3, verbose_name="Tiền tệ")),
                ("revenue_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))], verbose_name="Doanh thu chốt")),
                ("cargo_value", models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))], verbose_name="Giá trị hàng hóa")),
                ("cargo_value_currency", models.CharField(choices=[("VND", "VNĐ"), ("USD", "USD"), ("LAK", "Kíp Lào"), ("KHR", "Riel Campuchia")], default="USD", max_length=3, verbose_name="Tiền tệ giá trị hàng")),
                ("exchange_rate_to_vnd", models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))], verbose_name="Tỷ giá sang VNĐ")),
                ("usd_exchange_rate_vnd", models.DecimalField(decimal_places=2, default=25000, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))], verbose_name="Tỷ giá USD/VNĐ")),
                ("deposit_required", models.BooleanField(default=False, verbose_name="Yêu cầu đặt cọc")),
                ("deposit_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0"))], verbose_name="Tiền cọc yêu cầu")),
                ("credit_terms_days", models.PositiveSmallIntegerField(default=0, verbose_name="Số ngày công nợ")),
                ("payment_due_at", models.DateTimeField(blank=True, null=True, verbose_name="Hạn thanh toán")),
                ("credit_approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm duyệt công nợ")),
                ("contract_status", models.CharField(choices=[("none", "Không yêu cầu"), ("required", "Cần lập"), ("draft", "Đang soạn"), ("review", "Chờ duyệt"), ("signed", "Đã ký")], default="none", max_length=20, verbose_name="Trạng thái hợp đồng")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm hoàn thành")),
                ("settlement_due_at", models.DateTimeField(blank=True, null=True, verbose_name="Hạn nộp quyết toán")),
                ("settled_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm đã quyết toán")),
                ("revenue_recorded_at", models.DateTimeField(blank=True, null=True, verbose_name="Thời điểm ghi nhận doanh thu")),
                ("note", models.TextField(blank=True, verbose_name="Ghi chú tài chính")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credit_approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Người duyệt công nợ")),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="finance", to="crm.order", verbose_name="Đơn hàng")),
                ("revenue_recorded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Người ghi nhận doanh thu")),
            ],
            options={"verbose_name": "Tài chính đơn hàng", "verbose_name_plural": "Tài chính đơn hàng", "ordering": ["-order__created_at"]},
        ),
        migrations.CreateModel(
            name="OrderDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(choices=[("contract", "Hợp đồng"), ("invoice", "Hóa đơn"), ("customs", "Tờ khai hải quan"), ("pod", "Biên bản giao hàng"), ("image", "Hình ảnh hàng"), ("other", "Khác")], max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="order_documents/%Y/%m/")),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("finance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="finance.orderfinance")),
            ],
            options={"verbose_name": "Chứng từ đơn hàng", "verbose_name_plural": "Chứng từ đơn hàng", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderCost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("pickup", "Xe lấy hàng"), ("delivery", "Xe giao hàng"), ("warehouse", "Kho bãi"), ("loading", "Bốc xếp"), ("packing", "Đóng gói"), ("cross_border", "Qua biên giới"), ("customs", "Hải quan"), ("insurance", "Bảo hiểm"), ("cod", "Thu hộ"), ("other", "Khác")], max_length=30)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("currency", models.CharField(choices=[("VND", "VNĐ"), ("USD", "USD"), ("LAK", "Kíp Lào"), ("KHR", "Riel Campuchia")], default="VND", max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("incurred_at", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("supplier", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_costs", to="crm.partner")),
                ("finance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="costs", to="finance.orderfinance")),
            ],
            options={"verbose_name": "Chi phí đơn hàng", "verbose_name_plural": "Chi phí đơn hàng", "ordering": ["-incurred_at", "-id"]},
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_type", models.CharField(choices=[("deposit", "Tiền cọc"), ("collection", "Thu thanh toán"), ("cod", "Thu hộ COD"), ("refund", "Hoàn tiền khách")], max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("currency", models.CharField(choices=[("VND", "VNĐ"), ("USD", "USD"), ("LAK", "Kíp Lào"), ("KHR", "Riel Campuchia")], default="VND", max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))])),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finance", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="finance.orderfinance")),
                ("recorded_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
            ],
            options={"verbose_name": "Khoản thu đơn hàng", "verbose_name_plural": "Khoản thu đơn hàng", "ordering": ["-paid_at", "-id"]},
        ),
        migrations.RunPython(create_finance_records, migrations.RunPython.noop),
    ]
