# Generated by Django 5.1.4 on 2026-09-17 09:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_partner_companies'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='category',
            field=models.CharField(choices=[('pickup', 'Xe lấy hàng'), ('delivery', 'Xe giao hàng'), ('warehouse', 'Kho bãi'), ('loading', 'Bốc xếp'), ('packing', 'Đóng gói'), ('cross_border', 'Qua biên giới'), ('customs', 'Hải quan'), ('insurance', 'Bảo hiểm'), ('cod', 'Thu hộ'), ('other', 'Khác')], max_length=30, verbose_name='Loại chi phí'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='currency',
            field=models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD'), ('LAK', 'Kíp Lào'), ('KHR', 'Riel Campuchia')], default='VND', max_length=3, verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tỷ giá'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='finance.orderfinance', verbose_name='Hồ sơ tài chính đơn hàng'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='incurred_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Ngày phát sinh'),
        ),
        migrations.AlterField(
            model_name='ordercost',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_costs', to='crm.partner', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Số chứng từ'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='document_type',
            field=models.CharField(choices=[('contract', 'Hợp đồng'), ('invoice', 'Hóa đơn'), ('customs', 'Tờ khai hải quan'), ('pod', 'Biên bản giao hàng'), ('image', 'Hình ảnh hàng'), ('other', 'Khác')], max_length=20, verbose_name='Loại chứng từ'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='file',
            field=models.FileField(upload_to='order_documents/%Y/%m/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.orderfinance', verbose_name='Hồ sơ tài chính đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='orderdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên'),
        ),
        migrations.AlterField(
            model_name='orderfinance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='currency',
            field=models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD'), ('LAK', 'Kíp Lào'), ('KHR', 'Riel Campuchia')], default='VND', max_length=3, verbose_name='Tiền tệ'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tỷ giá'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='finance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.orderfinance', verbose_name='Hồ sơ tài chính đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày thanh toán'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_type',
            field=models.CharField(choices=[('deposit', 'Tiền cọc'), ('collection', 'Thu thanh toán'), ('cod', 'Thu hộ COD'), ('refund', 'Hoàn tiền khách')], max_length=20, verbose_name='Loại thanh toán'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người ghi nhận'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Số tham chiếu'),
        ),
    ]
