# Generated by Django 5.1.4 on 2026-09-12 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('crm', '0033_activity_company_kpitarget_company_notice_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='Mã hàng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên hàng hoá')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='ĐVT')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giá vốn tham khảo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giá bán mặc định')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Hàng hoá',
                'verbose_name_plural': 'Hàng hoá',
                'ordering': ['sku'],
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên kho')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company', verbose_name='Công ty')),
            ],
            options={
                'verbose_name': 'Kho hàng',
                'verbose_name_plural': 'Kho hàng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho'), ('adjustment', 'Điều chỉnh')], max_length=20, verbose_name='Loại')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Giá vốn')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product', verbose_name='Hàng hoá')),
                ('reference_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.orderitem', verbose_name='Dòng đơn hàng liên quan')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.partner', verbose_name='Nhà cung cấp')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse', verbose_name='Kho hàng')),
            ],
            options={
                'verbose_name': 'Nhật ký kho',
                'verbose_name_plural': 'Nhật ký kho',
                'ordering': ['-created_at'],
            },
        ),
    ]
