# Generated by Django 5.1.4 on 2026-09-21 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_alter_pricerequest_options_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Nhập kho'), ('out', 'Xuất kho'), ('transfer_out', 'Điều chuyển kho'), ('transfer_in', 'Nhập điều chuyển'), ('adjustment_up', 'Điều chỉnh tăng'), ('adjustment_down', 'Điều chỉnh giảm'), ('return', 'Trả hàng'), ('disposal', 'Huỷ hàng')], max_length=20, verbose_name='Loại'),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số lượng giữ')),
                ('status', models.CharField(choices=[('active', 'Đang giữ'), ('released', 'Đã huỷ giữ'), ('consumed', 'Đã xuất kho')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm huỷ giữ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('price_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='crm.pricerequestitem', verbose_name='Dòng yêu cầu giá')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.product', verbose_name='Hàng hoá')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='inventory.warehouse', verbose_name='Kho hàng')),
            ],
            options={
                'verbose_name': 'Giữ hàng',
                'verbose_name_plural': 'Giữ hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Mã lô')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Giá mua')),
                ('origin_point', models.CharField(blank=True, max_length=255, verbose_name='Điểm xuất phát')),
                ('shipped_at', models.DateField(blank=True, null=True, verbose_name='Ngày giao')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='Ngày nhập kho')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='inventory.product', verbose_name='Hàng hoá')),
                ('purchase_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='crm.purchaserequestitem', verbose_name='Dòng đề nghị mua')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.partner', verbose_name='Nhà cung cấp')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='inventory.warehouse', verbose_name='Kho nhận')),
            ],
            options={
                'verbose_name': 'Lô hàng',
                'verbose_name_plural': 'Lô hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.lot', verbose_name='Lô hàng'),
        ),
        migrations.CreateModel(
            name='LotCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hang_hoa', 'Tiền hàng'), ('van_chuyen', 'Vận chuyển'), ('hai_quan', 'Hải quan'), ('khac', 'Chi phí khác')], max_length=20, verbose_name='Loại chi phí')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Số tiền')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='inventory.lot', verbose_name='Lô hàng')),
            ],
            options={
                'verbose_name': 'Chi phí lô hàng',
                'verbose_name_plural': 'Chi phí lô hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
