# Generated by Django 5.1.4 on 2026-09-21 01:46

import companies.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_cavi_avi_into_livi'),
        ('inventory', '0003_migrate_adjustment_movement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company', verbose_name='Công ty'),
        ),
    ]
