# Generated by Django 5.1.4 on 2026-09-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_company_alter_warehouse_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/%Y/%m/', verbose_name='Hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='Hàng hoá')),
            ],
            options={
                'verbose_name': 'Hình ảnh hàng hoá',
                'verbose_name_plural': 'Hình ảnh hàng hoá',
                'ordering': ['created_at'],
            },
        ),
    ]
