# Generated by Django 5.1.4 on 2026-09-12 00:07

from django.db import migrations, models

# Seed ngay trong migration đầu tiên (không đợi chạy riêng seed_companies) — để các migration
# backfill company ở app khác (hr/crm/ops/approvals) gọi Company.objects.get(code="CAVI") được
# ngay từ migration kế tiếp, không phụ thuộc thứ tự chạy management command thủ công.
SEED_COMPANIES = [
    ("CAVI", "CAVI", "transport"),
    ("LIVI", "LIVI", "trading"),
    ("AVI", "AVI", "trading"),
]


def seed_companies(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    for code, name, business_type in SEED_COMPANIES:
        Company.objects.get_or_create(code=code, defaults={"name": name, "business_type": business_type})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên công ty')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã công ty')),
                ('business_type', models.CharField(choices=[('transport', 'Vận chuyển'), ('trading', 'Thương mại')], max_length=20, verbose_name='Loại hình')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Tên pháp lý')),
                ('tax_code', models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế')),
                ('hotline', models.CharField(blank=True, max_length=32, verbose_name='Hotline')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('logo', models.FileField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Công ty',
                'verbose_name_plural': 'Công ty',
                'ordering': ['business_type', 'name'],
            },
        ),
        migrations.RunPython(seed_companies, noop_reverse),
    ]
