# Generated by Django 5.1.4 on 2026-09-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at'], 'verbose_name': 'Công ty', 'verbose_name_plural': 'Công ty'},
        ),
    ]
