// Danh sách mã vùng điện thoại quốc tế (chuẩn ITU-T E.164).
// Thứ tự: 3 nước chính công ty làm việc (Việt Nam, Campuchia, Lào) lên đầu,
// Trung Quốc thứ 4, còn lại xếp theo alphabet tên tiếng Việt.
//
// `len: [min, max]` — số chữ số hợp lệ của "số thuê bao" (không tính số 0 đầu,
// không tính mã nước) theo chuẩn từng quốc gia — dùng để chặn nhập sai/thừa số.
// Nước nào chưa liệt kê thì dùng DEFAULT_LEN.
export const DEFAULT_LEN = [7, 11];

export const COUNTRY_CODES = [
  { code: "VN", name: "Việt Nam", dial: "+84", flag: "🇻🇳", len: [9, 10] },
  { code: "KH", name: "Campuchia", dial: "+855", flag: "🇰🇭", len: [8, 9] },
  { code: "LA", name: "Lào", dial: "+856", flag: "🇱🇦", len: [8, 10] },
  { code: "CN", name: "Trung Quốc", dial: "+86", flag: "🇨🇳", len: [11, 11] },

  { code: "AF", name: "Afghanistan", dial: "+93", flag: "🇦🇫" },
  { code: "EG", name: "Ai Cập", dial: "+20", flag: "🇪🇬" },
  { code: "IN", name: "Ấn Độ", dial: "+91", flag: "🇮🇳", len: [10, 10] },
  { code: "AL", name: "Albania", dial: "+355", flag: "🇦🇱" },
  { code: "DZ", name: "Algeria", dial: "+213", flag: "🇩🇿" },
  { code: "GB", name: "Anh", dial: "+44", flag: "🇬🇧", len: [10, 10] },
  { code: "AO", name: "Angola", dial: "+244", flag: "🇦🇴" },
  { code: "AR", name: "Argentina", dial: "+54", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", dial: "+374", flag: "🇦🇲" },
  { code: "AT", name: "Áo", dial: "+43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaijan", dial: "+994", flag: "🇦🇿" },
  { code: "SA", name: "Ả Rập Xê Út", dial: "+966", flag: "🇸🇦", len: [9, 9] },
  { code: "AE", name: "Ả Rập Thống Nhất (UAE)", dial: "+971", flag: "🇦🇪", len: [9, 9] },
  { code: "PL", name: "Ba Lan", dial: "+48", flag: "🇵🇱" },
  { code: "BS", name: "Bahamas", dial: "+1242", flag: "🇧🇸" },
  { code: "BH", name: "Bahrain", dial: "+973", flag: "🇧🇭" },
  { code: "BD", name: "Bangladesh", dial: "+880", flag: "🇧🇩" },
  { code: "BY", name: "Belarus", dial: "+375", flag: "🇧🇾" },
  { code: "BE", name: "Bỉ", dial: "+32", flag: "🇧🇪" },
  { code: "BJ", name: "Benin", dial: "+229", flag: "🇧🇯" },
  { code: "BT", name: "Bhutan", dial: "+975", flag: "🇧🇹" },
  { code: "BO", name: "Bolivia", dial: "+591", flag: "🇧🇴" },
  { code: "PT", name: "Bồ Đào Nha", dial: "+351", flag: "🇵🇹" },
  { code: "BA", name: "Bosnia và Herzegovina", dial: "+387", flag: "🇧🇦" },
  { code: "BW", name: "Botswana", dial: "+267", flag: "🇧🇼" },
  { code: "BR", name: "Brazil", dial: "+55", flag: "🇧🇷" },
  { code: "BN", name: "Brunei", dial: "+673", flag: "🇧🇳" },
  { code: "BG", name: "Bulgaria", dial: "+359", flag: "🇧🇬" },
  { code: "BF", name: "Burkina Faso", dial: "+226", flag: "🇧🇫" },
  { code: "BI", name: "Burundi", dial: "+257", flag: "🇧🇮" },
  { code: "CV", name: "Cabo Verde", dial: "+238", flag: "🇨🇻" },
  { code: "CA", name: "Canada", dial: "+1", flag: "🇨🇦" },
  { code: "CM", name: "Cameroon", dial: "+237", flag: "🇨🇲" },
  { code: "TD", name: "Chad", dial: "+235", flag: "🇹🇩" },
  { code: "CL", name: "Chile", dial: "+56", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", dial: "+57", flag: "🇨🇴" },
  { code: "KM", name: "Comoros", dial: "+269", flag: "🇰🇲" },
  { code: "CG", name: "Congo", dial: "+242", flag: "🇨🇬" },
  { code: "CD", name: "Congo (DR)", dial: "+243", flag: "🇨🇩" },
  { code: "CR", name: "Costa Rica", dial: "+506", flag: "🇨🇷" },
  { code: "HR", name: "Croatia", dial: "+385", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", dial: "+53", flag: "🇨🇺" },
  { code: "CZ", name: "Cộng hoà Séc", dial: "+420", flag: "🇨🇿" },
  { code: "DO", name: "Cộng hoà Dominica", dial: "+1809", flag: "🇩🇴" },
  { code: "DK", name: "Đan Mạch", dial: "+45", flag: "🇩🇰" },
  { code: "TW", name: "Đài Loan", dial: "+886", flag: "🇹🇼", len: [9, 9] },
  { code: "TL", name: "Đông Timor", dial: "+670", flag: "🇹🇱" },
  { code: "DE", name: "Đức", dial: "+49", flag: "🇩🇪", len: [10, 11] },
  { code: "DJ", name: "Djibouti", dial: "+253", flag: "🇩🇯" },
  { code: "DM", name: "Dominica", dial: "+1767", flag: "🇩🇲" },
  { code: "EC", name: "Ecuador", dial: "+593", flag: "🇪🇨" },
  { code: "SV", name: "El Salvador", dial: "+503", flag: "🇸🇻" },
  { code: "ER", name: "Eritrea", dial: "+291", flag: "🇪🇷" },
  { code: "EE", name: "Estonia", dial: "+372", flag: "🇪🇪" },
  { code: "ET", name: "Ethiopia", dial: "+251", flag: "🇪🇹" },
  { code: "PH", name: "Philippines", dial: "+63", flag: "🇵🇭", len: [10, 10] },
  { code: "FI", name: "Phần Lan", dial: "+358", flag: "🇫🇮" },
  { code: "FR", name: "Pháp", dial: "+33", flag: "🇫🇷", len: [9, 9] },
  { code: "GA", name: "Gabon", dial: "+241", flag: "🇬🇦" },
  { code: "GM", name: "Gambia", dial: "+220", flag: "🇬🇲" },
  { code: "GE", name: "Georgia", dial: "+995", flag: "🇬🇪" },
  { code: "GH", name: "Ghana", dial: "+233", flag: "🇬🇭" },
  { code: "GD", name: "Grenada", dial: "+1473", flag: "🇬🇩" },
  { code: "GT", name: "Guatemala", dial: "+502", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", dial: "+224", flag: "🇬🇳" },
  { code: "GW", name: "Guinea-Bissau", dial: "+245", flag: "🇬🇼" },
  { code: "GQ", name: "Guinea Xích Đạo", dial: "+240", flag: "🇬🇶" },
  { code: "GY", name: "Guyana", dial: "+592", flag: "🇬🇾" },
  { code: "NL", name: "Hà Lan", dial: "+31", flag: "🇳🇱" },
  { code: "KR", name: "Hàn Quốc", dial: "+82", flag: "🇰🇷", len: [9, 10] },
  { code: "HT", name: "Haiti", dial: "+509", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", dial: "+504", flag: "🇭🇳" },
  { code: "HU", name: "Hungary", dial: "+36", flag: "🇭🇺" },
  { code: "GR", name: "Hy Lạp", dial: "+30", flag: "🇬🇷" },
  { code: "IS", name: "Iceland", dial: "+354", flag: "🇮🇸" },
  { code: "ID", name: "Indonesia", dial: "+62", flag: "🇮🇩", len: [9, 12] },
  { code: "IE", name: "Ireland", dial: "+353", flag: "🇮🇪" },
  { code: "IR", name: "Iran", dial: "+98", flag: "🇮🇷" },
  { code: "IQ", name: "Iraq", dial: "+964", flag: "🇮🇶" },
  { code: "IL", name: "Israel", dial: "+972", flag: "🇮🇱" },
  { code: "IT", name: "Ý", dial: "+39", flag: "🇮🇹" },
  { code: "JM", name: "Jamaica", dial: "+1876", flag: "🇯🇲" },
  { code: "JO", name: "Jordan", dial: "+962", flag: "🇯🇴" },
  { code: "KZ", name: "Kazakhstan", dial: "+7", flag: "🇰🇿" },
  { code: "KE", name: "Kenya", dial: "+254", flag: "🇰🇪" },
  { code: "KI", name: "Kiribati", dial: "+686", flag: "🇰🇮" },
  { code: "KW", name: "Kuwait", dial: "+965", flag: "🇰🇼" },
  { code: "KG", name: "Kyrgyzstan", dial: "+996", flag: "🇰🇬" },
  { code: "LV", name: "Latvia", dial: "+371", flag: "🇱🇻" },
  { code: "LB", name: "Lebanon", dial: "+961", flag: "🇱🇧" },
  { code: "LS", name: "Lesotho", dial: "+266", flag: "🇱🇸" },
  { code: "LR", name: "Liberia", dial: "+231", flag: "🇱🇷" },
  { code: "LY", name: "Libya", dial: "+218", flag: "🇱🇾" },
  { code: "LI", name: "Liechtenstein", dial: "+423", flag: "🇱🇮" },
  { code: "LT", name: "Lithuania", dial: "+370", flag: "🇱🇹" },
  { code: "LU", name: "Luxembourg", dial: "+352", flag: "🇱🇺" },
  { code: "MO", name: "Ma Cao", dial: "+853", flag: "🇲🇴" },
  { code: "MA", name: "Ma-rốc", dial: "+212", flag: "🇲🇦" },
  { code: "MK", name: "Macedonia", dial: "+389", flag: "🇲🇰" },
  { code: "MG", name: "Madagascar", dial: "+261", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", dial: "+265", flag: "🇲🇼" },
  { code: "MY", name: "Malaysia", dial: "+60", flag: "🇲🇾", len: [9, 10] },
  { code: "MV", name: "Maldives", dial: "+960", flag: "🇲🇻" },
  { code: "ML", name: "Mali", dial: "+223", flag: "🇲🇱" },
  { code: "MT", name: "Malta", dial: "+356", flag: "🇲🇹" },
  { code: "MR", name: "Mauritania", dial: "+222", flag: "🇲🇷" },
  { code: "MU", name: "Mauritius", dial: "+230", flag: "🇲🇺" },
  { code: "MX", name: "Mexico", dial: "+52", flag: "🇲🇽" },
  { code: "FM", name: "Micronesia", dial: "+691", flag: "🇫🇲" },
  { code: "MD", name: "Moldova", dial: "+373", flag: "🇲🇩" },
  { code: "MC", name: "Monaco", dial: "+377", flag: "🇲🇨" },
  { code: "MN", name: "Mông Cổ", dial: "+976", flag: "🇲🇳" },
  { code: "ME", name: "Montenegro", dial: "+382", flag: "🇲🇪" },
  { code: "MZ", name: "Mozambique", dial: "+258", flag: "🇲🇿" },
  { code: "US", name: "Mỹ", dial: "+1", flag: "🇺🇸", len: [10, 10] },
  { code: "MM", name: "Myanmar", dial: "+95", flag: "🇲🇲" },
  { code: "NA", name: "Namibia", dial: "+264", flag: "🇳🇦" },
  { code: "NR", name: "Nauru", dial: "+674", flag: "🇳🇷" },
  { code: "ZA", name: "Nam Phi", dial: "+27", flag: "🇿🇦" },
  { code: "SS", name: "Nam Sudan", dial: "+211", flag: "🇸🇸" },
  { code: "NP", name: "Nepal", dial: "+977", flag: "🇳🇵" },
  { code: "RU", name: "Nga", dial: "+7", flag: "🇷🇺", len: [10, 10] },
  { code: "JP", name: "Nhật Bản", dial: "+81", flag: "🇯🇵", len: [9, 10] },
  { code: "NI", name: "Nicaragua", dial: "+505", flag: "🇳🇮" },
  { code: "NE", name: "Niger", dial: "+227", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "🇳🇬" },
  { code: "NO", name: "Na Uy", dial: "+47", flag: "🇳🇴" },
  { code: "NZ", name: "New Zealand", dial: "+64", flag: "🇳🇿" },
  { code: "OM", name: "Oman", dial: "+968", flag: "🇴🇲" },
  { code: "PK", name: "Pakistan", dial: "+92", flag: "🇵🇰" },
  { code: "PW", name: "Palau", dial: "+680", flag: "🇵🇼" },
  { code: "PS", name: "Palestine", dial: "+970", flag: "🇵🇸" },
  { code: "PA", name: "Panama", dial: "+507", flag: "🇵🇦" },
  { code: "PG", name: "Papua New Guinea", dial: "+675", flag: "🇵🇬" },
  { code: "PY", name: "Paraguay", dial: "+595", flag: "🇵🇾" },
  { code: "PE", name: "Peru", dial: "+51", flag: "🇵🇪" },
  { code: "QA", name: "Qatar", dial: "+974", flag: "🇶🇦" },
  { code: "RO", name: "Romania", dial: "+40", flag: "🇷🇴" },
  { code: "RW", name: "Rwanda", dial: "+250", flag: "🇷🇼" },
  { code: "WS", name: "Samoa", dial: "+685", flag: "🇼🇸" },
  { code: "SM", name: "San Marino", dial: "+378", flag: "🇸🇲" },
  { code: "ST", name: "Sao Tome và Principe", dial: "+239", flag: "🇸🇹" },
  { code: "SN", name: "Senegal", dial: "+221", flag: "🇸🇳" },
  { code: "RS", name: "Serbia", dial: "+381", flag: "🇷🇸" },
  { code: "SC", name: "Seychelles", dial: "+248", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", dial: "+232", flag: "🇸🇱" },
  { code: "SG", name: "Singapore", dial: "+65", flag: "🇸🇬", len: [8, 8] },
  { code: "SK", name: "Slovakia", dial: "+421", flag: "🇸🇰" },
  { code: "SI", name: "Slovenia", dial: "+386", flag: "🇸🇮" },
  { code: "SB", name: "Solomon Islands", dial: "+677", flag: "🇸🇧" },
  { code: "SO", name: "Somalia", dial: "+252", flag: "🇸🇴" },
  { code: "ES", name: "Tây Ban Nha", dial: "+34", flag: "🇪🇸" },
  { code: "LK", name: "Sri Lanka", dial: "+94", flag: "🇱🇰" },
  { code: "SD", name: "Sudan", dial: "+249", flag: "🇸🇩" },
  { code: "SR", name: "Suriname", dial: "+597", flag: "🇸🇷" },
  { code: "SE", name: "Thuỵ Điển", dial: "+46", flag: "🇸🇪" },
  { code: "CH", name: "Thuỵ Sĩ", dial: "+41", flag: "🇨🇭" },
  { code: "SZ", name: "Swaziland (Eswatini)", dial: "+268", flag: "🇸🇿" },
  { code: "SY", name: "Syria", dial: "+963", flag: "🇸🇾" },
  { code: "CY", name: "Síp", dial: "+357", flag: "🇨🇾" },
  { code: "TJ", name: "Tajikistan", dial: "+992", flag: "🇹🇯" },
  { code: "TZ", name: "Tanzania", dial: "+255", flag: "🇹🇿" },
  { code: "TH", name: "Thái Lan", dial: "+66", flag: "🇹🇭", len: [9, 9] },
  { code: "TG", name: "Togo", dial: "+228", flag: "🇹🇬" },
  { code: "TO", name: "Tonga", dial: "+676", flag: "🇹🇴" },
  { code: "TT", name: "Trinidad và Tobago", dial: "+1868", flag: "🇹🇹" },
  { code: "TR", name: "Thổ Nhĩ Kỳ", dial: "+90", flag: "🇹🇷" },
  { code: "TN", name: "Tunisia", dial: "+216", flag: "🇹🇳" },
  { code: "TM", name: "Turkmenistan", dial: "+993", flag: "🇹🇲" },
  { code: "TV", name: "Tuvalu", dial: "+688", flag: "🇹🇻" },
  { code: "UG", name: "Uganda", dial: "+256", flag: "🇺🇬" },
  { code: "UA", name: "Ukraine", dial: "+380", flag: "🇺🇦" },
  { code: "UY", name: "Uruguay", dial: "+598", flag: "🇺🇾" },
  { code: "UZ", name: "Uzbekistan", dial: "+998", flag: "🇺🇿" },
  { code: "AU", name: "Úc", dial: "+61", flag: "🇦🇺", len: [9, 9] },
  { code: "VU", name: "Vanuatu", dial: "+678", flag: "🇻🇺" },
  { code: "VE", name: "Venezuela", dial: "+58", flag: "🇻🇪" },
  { code: "YE", name: "Yemen", dial: "+967", flag: "🇾🇪" },
  { code: "ZM", name: "Zambia", dial: "+260", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", dial: "+263", flag: "🇿🇼" },
];

export const DEFAULT_COUNTRY = COUNTRY_CODES[0]; // Việt Nam

// Tách 1 số điện thoại đầy đủ (vd "+84 912345678") thành { dial, local }.
// So khớp mã dài nhất trước để tránh nhầm (vd +1242 Bahamas so với +1 Mỹ/Canada).
export function parsePhone(full) {
  if (!full) return { dial: DEFAULT_COUNTRY.dial, local: "" };
  const trimmed = full.trim();
  if (!trimmed.startsWith("+")) return { dial: DEFAULT_COUNTRY.dial, local: trimmed };
  const sorted = [...COUNTRY_CODES].sort((a, b) => b.dial.length - a.dial.length);
  for (const c of sorted) {
    if (trimmed.startsWith(c.dial)) {
      return { dial: c.dial, local: trimmed.slice(c.dial.length).trim().replace(/^0+/, "") };
    }
  }
  return { dial: DEFAULT_COUNTRY.dial, local: trimmed };
}

export function formatPhone(dial, local) {
  const digits = local.replace(/\D/g, "").replace(/^0+/, "");
  if (!digits) return "";
  return `${dial} ${digits}`;
}
