# Generated by Django 5.1.4 on 2026-09-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=120)),
                ('digest', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('account', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=30)),
                ('period', models.CharField(blank=True, max_length=30)),
                ('content', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_id', 'digest'), name='hub_source_version')],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('cells', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll', to='companyhub.sourcesnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_row'), name='hub_payroll_source_row')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('code', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('source_company', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='unconfirmed', max_length=30)),
                ('fields', models.JSONField(default=list)),
                ('issues', models.JSONField(default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='companyhub.sourcesnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'source_row'), name='hub_employee_source_row')],
            },
        ),
    ]
