# Generated by Django 5.1.4 on 2026-09-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Mã')),
            ],
            options={
                'verbose_name': 'Quốc gia',
                'verbose_name_plural': 'Quốc gia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('code', models.CharField(max_length=10, verbose_name='Mã')),
                ('division_type', models.CharField(blank=True, max_length=50, verbose_name='Cấp hành chính')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='geo.country', verbose_name='Quốc gia')),
            ],
            options={
                'verbose_name': 'Tỉnh/Thành phố',
                'verbose_name_plural': 'Tỉnh/Thành phố',
                'ordering': ['name'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('code', models.CharField(max_length=10, verbose_name='Mã')),
                ('division_type', models.CharField(blank=True, max_length=50, verbose_name='Cấp hành chính')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo.province', verbose_name='Tỉnh/Thành phố')),
            ],
            options={
                'verbose_name': 'Quận/Huyện',
                'verbose_name_plural': 'Quận/Huyện',
                'ordering': ['name'],
                'unique_together': {('province', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên')),
                ('code', models.CharField(max_length=10, verbose_name='Mã')),
                ('division_type', models.CharField(blank=True, max_length=50, verbose_name='Cấp hành chính')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='geo.district', verbose_name='Quận/Huyện')),
            ],
            options={
                'verbose_name': 'Phường/Xã',
                'verbose_name_plural': 'Phường/Xã',
                'ordering': ['name'],
                'unique_together': {('district', 'code')},
            },
        ),
    ]
