# Generated by Django 5.1.4 on 2026-09-06 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0004_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50, verbose_name='Tuyến')),
                ('status', models.CharField(choices=[('gathering', 'Đang gom hàng'), ('gathered', 'Đã gom hàng đủ'), ('shipped', 'Đã gửi')], default='gathering', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Hàng hoá')),
                ('route', models.CharField(blank=True, max_length=50, verbose_name='Tuyến')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mã tracking')),
                ('kd_status', models.CharField(choices=[('new', 'Mới tạo'), ('pending_review', 'Chờ phòng ban duyệt'), ('done', 'Hoàn tất')], default='new', max_length=20, verbose_name='Kinh doanh')),
                ('cu_status', models.CharField(choices=[('new', 'Mới tạo'), ('in_progress', 'Chờ cung ứng'), ('done', 'Hoàn tất')], default='new', max_length=20, verbose_name='Cung ứng')),
                ('vh_status', models.CharField(choices=[('new', 'Mới tạo'), ('pending', 'Chờ ghi nhận'), ('gathering', 'Đang gom hàng'), ('gathered', 'Đã gom hàng đủ'), ('shipped', 'Đã gửi')], default='new', max_length=20, verbose_name='Vận hành')),
                ('kt_status', models.CharField(choices=[('not_recorded', 'Chưa ghi nhận DT'), ('recorded', 'Đã ghi nhận DT')], default='not_recorded', max_length=20, verbose_name='Kế toán')),
                ('currency', models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD')], default='VND', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Số tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='crm.partner')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='ops.shipmentbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
