# Generated by Django 5.1.4 on 2026-09-10 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_alter_activity_options_alter_kpitarget_options_and_more'),
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kiện hàng', 'verbose_name_plural': 'Kiện hàng'},
        ),
        migrations.AlterModelOptions(
            name='shipmentbatch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chuyến gom hàng', 'verbose_name_plural': 'Chuyến gom hàng'},
        ),
        migrations.AlterField(
            model_name='shipment',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='ops.shipmentbatch', verbose_name='Chuyến gom hàng'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='currency',
            field=models.CharField(choices=[('VND', 'VNĐ'), ('USD', 'USD')], default='VND', max_length=3, verbose_name='Đơn vị tiền tệ'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='crm.partner', verbose_name='Đối tác'),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách'),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='status',
            field=models.CharField(choices=[('gathering', 'Đang gom hàng'), ('gathered', 'Đã gom hàng đủ'), ('shipped', 'Đã gửi')], default='gathering', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
