# Generated by Django 5.1.4 on 2026-09-12 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('ops', '0003_shipment_company_shipmentbatch_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_batches', to='companies.company', verbose_name='Công ty'),
        ),
    ]
