# Generated by Django 5.1.4 on 2026-09-21 01:46

import companies.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_merge_cavi_avi_into_livi'),
        ('ops', '0004_alter_shipment_company_alter_shipmentbatch_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='companies.company', verbose_name='Công ty'),
        ),
        migrations.AlterField(
            model_name='shipmentbatch',
            name='company',
            field=models.ForeignKey(default=companies.utils.get_default_company_id, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_batches', to='companies.company', verbose_name='Công ty'),
        ),
    ]
